/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements/index'
import { Route as AnnouncementsAnnouncementIdRouteImport } from './routes/announcements/$announcementId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'
import { Route as DirectoryBusinessIdRouteImport } from './routes/directory/$businessId'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as OfficialsIndexRouteImport } from './routes/officials/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminBusinessesRouteImport } from './routes/_authenticated/admin/businesses'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated/admin/complaints'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminEmergencyRouteImport } from './routes/_authenticated/admin/emergency'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedBusinessesNewRouteImport } from './routes/_authenticated/businesses/new'
import { Route as AuthenticatedComplaintsNewRouteImport } from './routes/_authenticated/complaints/new'
import { Route as AuthenticatedDocumentsRequestRouteImport } from './routes/_authenticated/documents.request'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedBusinessesBusinessIdEditRouteImport } from './routes/_authenticated/businesses/$businessId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsAnnouncementIdRoute =
  AnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryBusinessIdRoute = DirectoryBusinessIdRouteImport.update({
  id: '/directory/$businessId',
  path: '/directory/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialsIndexRoute = OfficialsIndexRouteImport.update({
  id: '/officials/',
  path: '/officials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessesRoute =
  AuthenticatedAdminBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmergencyRoute =
  AuthenticatedAdminEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedBusinessesNewRoute =
  AuthenticatedBusinessesNewRouteImport.update({
    id: '/businesses/new',
    path: '/businesses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsNewRoute =
  AuthenticatedComplaintsNewRouteImport.update({
    id: '/complaints/new',
    path: '/complaints/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRequestRoute =
  AuthenticatedDocumentsRequestRouteImport.update({
    id: '/documents/request',
    path: '/documents/request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessesBusinessIdEditRoute =
  AuthenticatedBusinessesBusinessIdEditRouteImport.update({
    id: '/businesses/$businessId/edit',
    path: '/businesses/$businessId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/emergency': typeof EmergencyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/directory/$businessId': typeof DirectoryBusinessIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/map/': typeof MapIndexRoute
  '/officials/': typeof OfficialsIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/businesses/new': typeof AuthenticatedBusinessesNewRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/documents/request': typeof AuthenticatedDocumentsRequestRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/businesses/$businessId/edit': typeof AuthenticatedBusinessesBusinessIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/emergency': typeof EmergencyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/directory/$businessId': typeof DirectoryBusinessIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/events': typeof EventsIndexRoute
  '/map': typeof MapIndexRoute
  '/officials': typeof OfficialsIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/businesses/new': typeof AuthenticatedBusinessesNewRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/documents/request': typeof AuthenticatedDocumentsRequestRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/businesses/$businessId/edit': typeof AuthenticatedBusinessesBusinessIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/emergency': typeof EmergencyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/directory/$businessId': typeof DirectoryBusinessIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/map/': typeof MapIndexRoute
  '/officials/': typeof OfficialsIndexRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/businesses/new': typeof AuthenticatedBusinessesNewRoute
  '/_authenticated/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/_authenticated/documents/request': typeof AuthenticatedDocumentsRequestRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/businesses/$businessId/edit': typeof AuthenticatedBusinessesBusinessIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/emergency'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/announcements/$announcementId'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/directory/$businessId'
    | '/events/$eventId'
    | '/announcements/'
    | '/directory/'
    | '/events/'
    | '/map/'
    | '/officials/'
    | '/admin/announcements'
    | '/admin/businesses'
    | '/admin/complaints'
    | '/admin/documents'
    | '/admin/emergency'
    | '/admin/events'
    | '/admin/users'
    | '/businesses/new'
    | '/complaints/new'
    | '/documents/request'
    | '/settings/profile'
    | '/admin/'
    | '/businesses/$businessId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/emergency'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/notifications'
    | '/announcements/$announcementId'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/directory/$businessId'
    | '/events/$eventId'
    | '/announcements'
    | '/directory'
    | '/events'
    | '/map'
    | '/officials'
    | '/admin/announcements'
    | '/admin/businesses'
    | '/admin/complaints'
    | '/admin/documents'
    | '/admin/emergency'
    | '/admin/events'
    | '/admin/users'
    | '/businesses/new'
    | '/complaints/new'
    | '/documents/request'
    | '/settings/profile'
    | '/admin'
    | '/businesses/$businessId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/documents'
    | '/emergency'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/announcements/$announcementId'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/directory/$businessId'
    | '/events/$eventId'
    | '/announcements/'
    | '/directory/'
    | '/events/'
    | '/map/'
    | '/officials/'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/businesses'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/emergency'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/users'
    | '/_authenticated/businesses/new'
    | '/_authenticated/complaints/new'
    | '/_authenticated/documents/request'
    | '/_authenticated/settings/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/businesses/$businessId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  EmergencyRoute: typeof EmergencyRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AnnouncementsAnnouncementIdRoute: typeof AnnouncementsAnnouncementIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DirectoryBusinessIdRoute: typeof DirectoryBusinessIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  OfficialsIndexRoute: typeof OfficialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$announcementId': {
      id: '/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/announcements/$announcementId'
      preLoaderRoute: typeof AnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$businessId': {
      id: '/directory/$businessId'
      path: '/directory/$businessId'
      fullPath: '/directory/$businessId'
      preLoaderRoute: typeof DirectoryBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officials/': {
      id: '/officials/'
      path: '/officials'
      fullPath: '/officials/'
      preLoaderRoute: typeof OfficialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/businesses': {
      id: '/_authenticated/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emergency': {
      id: '/_authenticated/admin/emergency'
      path: '/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AuthenticatedAdminEmergencyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/businesses/new': {
      id: '/_authenticated/businesses/new'
      path: '/businesses/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof AuthenticatedBusinessesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/new': {
      id: '/_authenticated/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AuthenticatedComplaintsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/request': {
      id: '/_authenticated/documents/request'
      path: '/documents/request'
      fullPath: '/documents/request'
      preLoaderRoute: typeof AuthenticatedDocumentsRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/businesses/$businessId/edit': {
      id: '/_authenticated/businesses/$businessId/edit'
      path: '/businesses/$businessId/edit'
      fullPath: '/businesses/$businessId/edit'
      preLoaderRoute: typeof AuthenticatedBusinessesBusinessIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBusinessesRoute: typeof AuthenticatedAdminBusinessesRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminEmergencyRoute: typeof AuthenticatedAdminEmergencyRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBusinessesRoute: AuthenticatedAdminBusinessesRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminEmergencyRoute: AuthenticatedAdminEmergencyRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedBusinessesNewRoute: typeof AuthenticatedBusinessesNewRoute
  AuthenticatedComplaintsNewRoute: typeof AuthenticatedComplaintsNewRoute
  AuthenticatedDocumentsRequestRoute: typeof AuthenticatedDocumentsRequestRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedBusinessesBusinessIdEditRoute: typeof AuthenticatedBusinessesBusinessIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedBusinessesNewRoute: AuthenticatedBusinessesNewRoute,
  AuthenticatedComplaintsNewRoute: AuthenticatedComplaintsNewRoute,
  AuthenticatedDocumentsRequestRoute: AuthenticatedDocumentsRequestRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedBusinessesBusinessIdEditRoute:
    AuthenticatedBusinessesBusinessIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  EmergencyRoute: EmergencyRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AnnouncementsAnnouncementIdRoute: AnnouncementsAnnouncementIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DirectoryBusinessIdRoute: DirectoryBusinessIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MapIndexRoute: MapIndexRoute,
  OfficialsIndexRoute: OfficialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
